# Generated by Django 5.2.13 on 2026-04-23 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agent_creator_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='domain',
            field=models.CharField(default='general', help_text='Domain tag set by the orchestrator for agent matching', max_length=100),
        ),
        migrations.CreateModel(
            name='TaskRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=0, help_text='Orchestrator ranking: 1 = best fit')),
                ('reason', models.CharField(blank=True, default='', help_text='Why the orchestrator recommended this agent', max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='core.agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.task')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('task', 'agent')},
            },
        ),
    ]
