# Generated by Django 5.2.13 on 2026-04-24 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_domain_taskrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='description',
            new_name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='tier',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('research', 'Research'), ('summarization', 'Summarization'), ('translation', 'Translation'), ('data_analysis', 'Data Analysis'), ('code_generation', 'Code Generation'), ('image_processing', 'Image Processing'), ('document_drafting', 'Document Drafting'), ('web_search', 'Web Search'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='api_endpoint',
            field=models.URLField(blank=True, default='', help_text='Where Jarvis sends task payloads'),
        ),
        migrations.AddField(
            model_name='agent',
            name='auth_method',
            field=models.CharField(choices=[('api_key', 'API Key'), ('bearer_token', 'Bearer Token')], default='api_key', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='auth_secret',
            field=models.TextField(blank=True, default='', help_text='API key or Bearer token (stored encrypted in production)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='avg_completion_time',
            field=models.IntegerField(default=30, help_text='Estimated task completion time in seconds'),
        ),
        migrations.AddField(
            model_name='agent',
            name='base_price_per_task',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Base price in Credits', max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Capabilities, limitations, ideal task types (max 1000 chars)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_concurrent_tasks',
            field=models.IntegerField(default=5, help_text='Max tasks the agent can handle simultaneously'),
        ),
        migrations.AddField(
            model_name='agent',
            name='min_payout_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum earnings before payout (USD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='owner_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='payout_frequency',
            field=models.CharField(choices=[('per_task', 'Per Task'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='per_task', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='per_minute_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price per minute for audio/video', max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='per_page_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price per page for document tasks', max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='What the agent does (max 300 chars)', max_length=300),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('busy', 'Busy'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='supported_input_formats',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["text", "pdf", "image", "json"]'),
        ),
        migrations.AddField(
            model_name='agent',
            name='supported_output_formats',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["text", "json", "markdown"]'),
        ),
        migrations.AddField(
            model_name='agent',
            name='surge_pricing_enabled',
            field=models.BooleanField(default=False, help_text='Allow higher rates during high demand'),
        ),
        migrations.AddField(
            model_name='agent',
            name='trust_score',
            field=models.FloatField(default=0.0, help_text='0-100, assigned by Jarvis after vetting'),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='vetting_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='vetting_test_result',
            field=models.JSONField(blank=True, help_text='Results from automated sample task test', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='wallet_address',
            field=models.CharField(blank=True, default='', help_text='Arc wallet address for USDC payouts', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='User credit balance in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='True after user loads minimum $5 credits'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_low_credits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_task_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Used for WhatsApp output delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_delivery',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Both')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The developer/company who owns this agent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='domain',
            field=models.CharField(default='general', help_text='Primary domain for orchestrator matching', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='Agent display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='retrieval_depth',
            field=models.IntegerField(default=2, help_text='Number of RAG docs to retrieve from shared knowledge base'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USDC', max_length=10),
        ),
    ]
