# Generated by Django 5.2.13 on 2026-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=5, default=0.0, help_text='Platform earnings in USDC from matching fees', max_digits=14)),
                ('total_fees_collected', models.DecimalField(decimal_places=5, default=0.0, max_digits=14)),
                ('total_transactions', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Wallet',
            },
        ),
    ]
